// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUEHNTp_t5_8bDuuqMnoVOkvrHzyNQg0',
    appId: '1:679911614281:web:c1ff3e73bf3abaf1495c98',
    messagingSenderId: '679911614281',
    projectId: 'deeplink-32531',
    authDomain: 'deeplink-32531.firebaseapp.com',
    storageBucket: 'deeplink-32531.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTByCwiTSIBQ9vz3HNrRJDrYhLHegKwA',
    appId: '1:679911614281:android:db214e2a11e0fa8b495c98',
    messagingSenderId: '679911614281',
    projectId: 'deeplink-32531',
    storageBucket: 'deeplink-32531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBQEXegpF7Iij1InQq2bQf-fkCNOQb3w',
    appId: '1:679911614281:ios:49574017753bcfad495c98',
    messagingSenderId: '679911614281',
    projectId: 'deeplink-32531',
    storageBucket: 'deeplink-32531.appspot.com',
    iosClientId:
        '679911614281-0g0dfvank2o14sa6ikddnu62d85k0eqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBQEXegpF7Iij1InQq2bQf-fkCNOQb3w',
    appId: '1:679911614281:ios:49574017753bcfad495c98',
    messagingSenderId: '679911614281',
    projectId: 'deeplink-32531',
    storageBucket: 'deeplink-32531.appspot.com',
    iosClientId:
        '679911614281-0g0dfvank2o14sa6ikddnu62d85k0eqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplink',
  );
}
